'use strict'

module.exports = {
  zh: {
    1: '用户还没登录',
    2: '照片地址必须有',
    3: '性别必填',
    4: '邀请码不存在',
    5: '邀请码过期',
    6: '邀请码已被使用',
    7: '两次输入密码不一致',
    8: '验证码错误',
    9: '用户已存在',
    10: '尊敬的会员，您有查看和发送各10条消息权限',
    11: '尊贵的会员您好，欢迎加入boss直约，您需要尽快完善资料：1、您需要把您的资料完整度提升到90以上，才能获得发送信息的权限。2、系统会有专人对您的资料进行审核。3、审核通过后，其他会员可以搜索到您。4、请勿填写任何违反用户协议的内容。',
    12: '用户不存在',
    13: '密码错误',
    14: '该会员已经被封号',
    15: '照片识别错误，请确认照片是清晰的人脸',
    16: '人脸识别失败',
    17: '你的昵称和头像正在审核',
    19: '你已经被封号，请联系客服',
    20: '今天的10次浏览次数已用完',
    21: '今天的50次浏览次数已用完',
    22: '今天的100次浏览次数已用完',
    23: '今天的200次浏览次数已用完',
    24: '浏览了你',
    25: '有绅士浏览了你',
    26: '有甜心浏览了你',
    27: '没有更多数据了',
    28: '甜心',
    29: '绅士',
    30: '个性签名',
    31: '自我介绍',
    32: '职业描述',
    33: '昵称',
    34: '资料已经审核通过',
    35: '资料正在审核',
    36: '请选择图片或者文字',
    37: '你未有权限发心愿，请完善资料并审核通过后使用',
    38: '最多每天发两条心愿',
    39: '找不到该数据了',
    40: '你的心愿正在审核',
    41: '公开照片最多只能上传6张',
    42: '私照最多只能上传6张',
    43: '删除失败',
    44: '该用户没有邀请码',
    50:'查看10条信息权限已用完，请升级为会员',
    51:'你没权限查看消息，请升级为会员',
    52:'用户聊天对象id不存在',
    53:' 阅读了您的消息',
    54:'有绅士阅读了您的消息',
    55:'有甜心阅读了您的消息',
    56:'msg 或者 to 不能为空',
    57:'是敏感信息不允许发送',
    58:'该用户账号被封',
    59:'你的账号被封',
    60:'你已把对方屏蔽，无法发送',
    61:'你已被对方屏蔽，无法发送',
    62:'有绅士给您发了一条消息',
    63:'有甜心给您发了一条消息',
    64:'你收到一条新消息，请升级会员后查看',
    65:'ID为空',
    66:'找不到该消息',
    67:'删除成功',
    68:'私照请求已通过，到主页即可查看',
    69:'绅士私照请求已通过，到主页即可查看',
    70:'甜心私照请求已通过，到主页即可查看',
    71:'该用户已经允许你查看私照',
    72:'请求查看私照',
    73:'请求查看您的私照',
    74:'有绅士请求查看您的私照',
    75:'有甜心请求查看您的私照',
    76:'头像地址不能为空',
    77:'您在',
    78:'已经请求过了，请在',
    79:'分钟后尝试',
    80:'关注了你',
    81:'该举报对象不存在',
    82:'绅士',
    83:'甜心',
    84:'还没有选择vip类型',
    85:'90天会员资格',
    86:'14天会员使用期',
    87:'28天会员使用期',
    88:'60天会员使用期',
    89:'90天会员使用期',
    90:'你购买了',
    91:'天会员,享受',
    92:'天聊天权限',
    93:'你获得了',
    94:'邀请码一个',
    95:'于',
    96:'到期',
    97:'个性签名审核被拒绝,因为 ',
    98:'个性签名审核被拒绝,请尽快修改',
    99:'昵称审核被拒绝,因为',
    100:'昵称审核被拒绝,请尽快修改',
    101:'自我介绍审核被拒绝,因为 ',
    102:'自我介绍审核被拒绝,请尽快修改',
    103:'职业描述审核被拒绝,因为',
    104:'职业描述审核被拒绝,请尽快修改',
    105:'头像审核被拒绝,因为 ',
    106:'头像审核被拒绝,请尽快修改',
    107:'请尽快修改',
    108:'第',
    109:'张私照因为 ',
    110:'张公照因为 ',
    111:'审核被拒绝,请尽快修改',
    112:'张私照',
    113:'张公照',
    114:'给您发了一条消息',
    115:'你的资料通过审核',
    116:'心愿因为 ',
    117:'您的心愿通过审核',
    118:'您的查看10条信息的权限已经用完，请升级会员继续使用',
    119:'升级会员后才能使用',
    120:'你20条上限已经发送完毕，请升级会员继续使用',
    121:'发送10条信息权限已用完，请完善信息后继续使用',
    122:'请先完善个人资料',
    123:'7天会员使用期',
    124:'发送10条信息权限已用完，请升级会员继续使用'
  },
  en: {
    1: 'user unlogin',
    2: 'url required',
    3: 'gender required',
    4: 'Invitation code does not exist',
    5: 'Invitation code expires',
    6: 'Invitation code has been used',
    7: 'Two passwords are not consistent',
    8: 'Verification code error',
    9: 'The user already exists',
    10: 'Dear members, you have the right to view and send 10 messages',
    11: '1. You need to increase your information integrity to 90% to gain access to send message permissions   2. The system will have special people to audit your information   3. Your information has been reviewed, other members can search for you  4. Please do not fill in any violation of user agreement',
    12: 'User does not exist',
    13: 'wrong password',
    14: 'This has been banned',
    15: 'Photo identification error, please make sure the photo is clear face',
    16: 'Face recognition failed',
    17: 'Your nickname and picture are being reviewed',
    19: 'You have been banned , please contact customer service',
    20: 'Today\'s 10 visits have run out',
    21: 'Today\'s 50 visits have run out',
    22: 'Today\'s 100 visits have run out',
    23: 'Today\'s 200 visits have run out',
    24: 'have visited you',
    25: 'Some gentleman have browsed you',
    26: 'Some lady have browsed you',
    27: 'no more',
    28: 'lady',
    29: 'gentleman',
    30: 'Character',
    31: 'self-introduction',
    32: 'work',
    33: 'nickname',
    34: 'has been approved',
    35: 'is under review',
    36: 'Please select a picture or text',
    37: 'You do not have the right to make a wish, please improve the information and review first',
    38: 'Limit two daily wishes',
    39: 'Data not found',
    40: 'Your wish is under review',
    41: 'Public photos can only upload 6 sheets',
    42: 'Private photos can only upload 6 sheets',
    43: 'Failed to delete',
    44: 'The user has no invitation code',
    50:'ten free information has been used up, please upgrade to vip',
    51:'You do not have permission to view the message, please upgrade to a member',
    52:'User chat id does not exist',
    53:'Read your message',
    54:'A gentleman has read your message',
    55:'A lady read your message',
    56:'msg or chat object can not be empty',
    57:'is sensitive information is not allowed to be sent',
    58:'his user account is closed',
    59:'Your account is closed',
    60:'You have blocked each other and can not send it',
    61:'You have been blocked by the other party and can not send it',
    62:'A gentleman sent you a message',
    63:'A lady to send you a message',
    64:'You receive a new message, please upgrade the vip after the view',
    65:'ID is empty',
    66:'Can not find the message',
    67:'successfully deleted',
    68:'Private request has been passed to the home page to view',
    69:'Gentleman private request has been passed to the home page to view',
    70:'lady private request has been passed to the home page to view',
    71:'The user has allowed you to view private photos',
    72:'Request to view private photos',
    73:'Request to view your private photo',
    74:'Have a gentleman ask for your private photo',
    75:'Have a sweet request to view your private photo',
    76:'Avatar address can not be empty',
    77:'you have request in',
    78:'please in',
    79:'try again',
    80:'Concerned about you',
    81:'The reporting object does not exist',
    82:'gentleman',
    83:'lady',
    84:'has not selected vip type ',
    85:'90 days membership period',
    86:'14 days membership period',
    87:'28 days membership period',
    88:'60 days membership period',
    89:'90 days membership period',
    90:'You purchased ',
    91:'-day member to enjoy ',
    92:' of chatting',
    93:'You got it ',
    94:' an invitation code',
    95:'in',
    96:'maturity',
    97:'Individual signatures are rejected because of sensitive words',
    98:'Individual signature review is rejected, please modify as soon as possible',
    99:'Nickname review was rejected because',
    100:'Nickname review is rejected, please modify as soon as possible',
    101:'Self-introduction review was rejected because',
    102:'Self-introduction review is rejected, please modify as soon as possible',
    103:'Job description review was rejected because',
    104:'Job description review is rejected, please modify as soon as possible',
    105:'Avatar review was rejected because of',
    106:'Avatar review is rejected, please modify as soon as possible',
    107:'Please modify as soon as possible',
    108:'the',
    109:'Private photo because',
    110:'Public photo because',
    111:'the review is rejected, please modify it as soon as possible',
    112:'private photo',
    113:'public photo',
    114:' sent you a message',
    115:'Your information is reviewed',
    116:'the review because ',
    117:'You wish to pass the examination',
    118:'Your permission to view 10 messages has been used, please upgrade the members to continue to use',
    119:'Upgrade members before you read',
    120:'Your 20 cap has been sent, please upgrade members to continue to use',
    121:'Send 10 information authority has been used, please improve the information and continue to use',
    122:'Please improve your personal information first',
    123:'7 days membership period',
    124:'Your 10 cap has been sent, please upgrade members to continue to use'
  }
  ,ft: {
    1: '用戶還沒登錄',
    2: '照片地址必須有',
    3: '性別必填',
    4: '邀請碼不存在',
    5: '邀請碼過期',
    6: '邀請碼已被使用',
    7: '兩次輸入密碼不一致',
    8: '驗證碼錯誤',
    9: '用戶已存在',
	10: '尊敬的會員，您有查看和發送各10條消息權限',
	11: '尊貴的會員您好，歡迎加入boss直約，您需要盡快完善資料：1、您需要把您的資料完整度提升到90以上，才能獲得發送信息的權限。2、系統會有專人對您的資料進行審核。3、審核通過後，其他會員可以搜索到您。4、請勿填寫任何違反用戶協議的內容。',
	12: '用戶不存在',
	13: '密碼錯誤',
	14: '該會員已經被封號',
	15: '照片識別錯誤，請確認照片是清晰的人臉',
	16: '人臉識別失敗',
	17: '你的昵稱和頭像正在審核',
	19: '你已經被封號，請聯系客服',
	20: '今天的10次浏覽次數已用完',
	21: '今天的50次浏覽次數已用完',
	22: '今天的100次浏覽次數已用完',
	23: '今天的200次浏覽次數已用完',
	24: '浏覽了你',
	25: '有紳士浏覽了你',
	26: '有甜心浏覽了你',
	27: '沒有更多數據了',
	28: '甜心',
	29: '紳士',
	30: '個性簽名',
	31: '自我介紹',
	32: '職業描述',
	33: '昵稱',
	34: '資料已經審核通過',
	35: '資料正在審核',
	36: '請選擇圖片或者文字',
	37: '你未有權限發心願，請完善資料並審核通過後使用',
	38: '最多每天發兩條心願',
	39: '找不到該數據了',
	40: '你的心願正在審核',
	41: '公開照片最多只能上傳6張',
	42: '私照最多只能上傳6張',
	43: '刪除失敗',
	44: '該用戶沒有邀請碼',
	50:'查看10條信息權限已用完，請升級爲會員',
	51:'你沒權限查看消息，請升級爲會員',
	52:'用戶聊天對象id不存在',
	53:'閱讀了您的消息',
	54:'有紳士閱讀了您的消息',
	55:'有甜心閱讀了您的消息',
	56:'msg 或者 to 不能爲空',
	57:'是敏感信息不允許發送',
	58:'該用戶賬號被封',
	59:'你的賬號被封',
	60:'你已把對方屏蔽，無法發送',
	61:'你已被對方屏蔽，無法發送',
	62:'有紳士給您發了一條消息',
	63:'有甜心給您發了一條消息',
	64:'你收到一條新消息，請升級會員後查看',
	65:'ID爲空',
	66:'找不到該消息',
	67:'刪除成功',
	68:'私照請求已通過，到主頁即可查看',
	69:'紳士私照請求已通過，到主頁即可查看',
	70:'甜心私照請求已通過，到主頁即可查看',
	71:'該用戶已經允許你查看私照',
	72:'請求查看私照',
	73:'請求查看您的私照',
	74:'有紳士請求查看您的私照',
	75:'有甜心請求查看您的私照',
	76:'頭像地址不能爲空',
	77:'您在',
	78:'已經請求過了，請在',
	79:'後嘗試',
	80:'關注了你',
	81:'該舉報對象不存在',
	82:'紳士',
	83:'甜心',
	84:'還沒有選擇vip類型',
	85:'90天會員資格',
	86:'14天會員使用期',
	87:'28天會員使用期',
	88:'60天會員使用期',
	89:'90天會員使用期',
	90:'你購買了',
	91:'天會員,享受',
	92:'天聊天權限',
	93:'你獲得了',
	94:'邀請碼一個',
	95:'于',
	96:'到期',
	97:'個性簽名審核被拒絕,因爲 ',
	98:'個性簽名審核被拒絕,請盡快修改',
	99:'昵稱審核被拒絕,因爲',
	100:'昵稱審核被拒絕,請盡快修改',
	101:'自我介紹審核被拒絕,因爲 ',
	102:'自我介紹審核被拒絕,請盡快修改',
	103:'職業描述審核被拒絕,因爲 ',
	104:'職業描述審核被拒絕,請盡快修改',
	105:'頭像審核被拒絕,因爲 ',
	106:'頭像審核被拒絕,請盡快修改',
	107:'請盡快修改',
	108:'第',
	109:'張私照因爲 ',
	110:'張公照因爲 ',
	111:'審核被拒絕,請盡快修改',
	112:'張私照',
	113:'張公照',
    114:'給您發了一條消息',
    115:'您的資料通過審核',
    116:'心願因爲 ',
    117:'你的心願通過審核',
    118:'您的查看10條信息的權限已經用完，請升級會員繼續使用',
    119:'升級會員後才能使用',
    120:'你20條上限已經發送完畢，請升級會員繼續使用',
    121:'發送10條信息權限已用完，請完善信息後繼續使用',
    122:'請先完善個人資料',
    123:'7天會員使用期',
    124:'你10條上限已經發送完畢，請升級會員繼續使用'
  }
}
